import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Area, AreaChart, Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowDownRight, ArrowUpRight, CalendarDays, CheckCircle2, IndianRupee, Landmark, ReceiptText, RefreshCcw, ShieldCheck, Sparkles, WalletCards, Zap } from 'lucide-react';
import { api } from '../api';
import { rupee, currentMonth } from '../lib';
import { Badge, Card, EmptyState, Input, Reveal, Surface } from '../components/ui';

const colors = ['#59f3c3','#ffb454','#60a5fa','#f472b6','#a78bfa','#f87171','#34d399','#facc15'];
const tooltip = {background:'#06100e', border:'1px solid rgba(255,255,255,.12)', borderRadius:8, color:'#fff'};

function Metric({label,value,delta,icon:Icon,tone='default',delay=0}:{label:string;value:any;delta?:string;icon:any;tone?:'default'|'good'|'warn';delay?:number}){
  return <Reveal delay={delay}><Card className="group min-h-36 p-5 transition duration-300 hover:-translate-y-1 hover:border-emeraldx/28"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase text-white/38">{label}</p><div className="mt-4 text-2xl font-black leading-tight sm:text-3xl">{value}</div>{delta && <div className={`mt-3 inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-black ${tone==='warn'?'bg-saffronx/14 text-saffronx':tone==='good'?'bg-emeraldx/14 text-emeraldx':'bg-white/8 text-white/58'}`}>{tone==='warn'?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {delta}</div>}</div><div className="rounded-md border border-white/10 bg-white/8 p-2.5 text-emeraldx transition group-hover:scale-105"><Icon size={20}/></div></div></Card></Reveal>
}

function ChartEmpty({title}:{title:string}){return <div className="grid h-[280px] place-items-center rounded-md border border-dashed border-white/12 bg-black/16"><div className="text-center"><Sparkles className="mx-auto text-emeraldx/70"/><p className="mt-3 text-sm font-bold text-white/60">{title}</p><p className="mt-1 text-xs text-white/35">Upload or confirm transactions to populate this view.</p></div></div>}

export default function Dashboard(){
  const [month,setMonth]=useState(currentMonth());
  const {data:s={}}=useQuery({queryKey:['summary',month], queryFn:()=>api.summary(month)});
  const {data:c={category:[],daily:[],merchant:[],mode:[],card:[]}}=useQuery({queryKey:['charts',month], queryFn:()=>api.charts(month)});
  const total = Number(s.total_spend || 0);
  const budget = Number(s.budget_progress || 0);
  const hasDaily = (c.daily?.length || 0) > 0;
  const hasCategory = (c.category?.length || 0) > 0;
  const hasMerchant = (c.merchant?.length || 0) > 0;

  return <div className="space-y-8">
    <Reveal><Card className="relative overflow-hidden p-6 sm:p-8 lg:p-9"><div className="absolute inset-y-0 right-0 w-1/2 bg-[radial-gradient(circle_at_60%_30%,rgba(89,243,195,.16),transparent_18rem)]"/><div className="relative grid gap-7 xl:grid-cols-[1.15fr_.85fr]"><div><div className="flex flex-wrap items-center gap-2"><Badge tone="good">Command Center</Badge><Badge>{month}</Badge><Badge tone={budget > 95 ? 'danger' : budget > 75 ? 'warn' : 'default'}>{budget || 0}% budget used</Badge></div><h2 className="mt-5 max-w-3xl text-4xl font-black leading-[1.04] sm:text-5xl lg:text-6xl">{rupee(total)} <span className="block text-white/48">actual spend mapped.</span></h2><p className="mt-5 max-w-2xl text-sm leading-6 text-white/58">Actual expense excludes card payments, self-transfers, duplicate rows, and other money movement noise. Start here, then drill into merchants and transactions.</p><div className="mt-7 flex flex-wrap gap-3"><Surface className="px-4 py-3"><div className="text-xs text-white/38">Top category</div><div className="mt-1 font-black">{s.top_category || 'None'}</div></Surface><Surface className="px-4 py-3"><div className="text-xs text-white/38">Top merchant</div><div className="mt-1 font-black">{s.top_merchant || 'None'}</div></Surface><Surface className="px-4 py-3"><div className="text-xs text-white/38">Refunds</div><div className="mt-1 font-black text-emeraldx">{rupee(s.refunds)}</div></Surface></div></div><div className="grid content-between gap-4"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black uppercase text-white/38">Month selector</p><p className="mt-1 text-sm text-white/55">Review one statement month at a time.</p></div><CalendarDays className="text-saffronx"/></div><Input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><div className="grid grid-cols-2 gap-3"><Surface><div className="text-xs text-white/38">Weekend</div><div className="mt-2 text-xl font-black">{rupee(s.weekend_spend)}</div></Surface><Surface><div className="text-xs text-white/38">Weekday</div><div className="mt-2 text-xl font-black">{rupee(s.weekday_spend)}</div></Surface></div></div></div></Card></Reveal>

    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Credit card" value={rupee(s.credit_card_spend)} icon={WalletCards} delay={.03}/><Metric label="UPI spend" value={rupee(s.upi_spend)} icon={Zap} tone="warn" delta="quick taps" delay={.06}/><Metric label="Excluded movement" value={rupee(s.excluded_transfers)} icon={RefreshCcw} tone="good" delta="removed" delay={.09}/><Metric label="Manual/cash" value={rupee(s.manual_spend)} icon={IndianRupee} delay={.12}/></section>

    <section className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><Reveal><Card className="p-6 sm:p-7"><div className="mb-6 flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-2xl font-black">Daily spend rhythm</h3><p className="mt-1 text-sm text-white/45">The month as a pulse, not a pile of rows.</p></div><Badge>included spend only</Badge></div>{hasDaily ? <ResponsiveContainer width="100%" height={330}><AreaChart data={c.daily} margin={{left:0,right:18,top:12,bottom:0}}><defs><linearGradient id="dailyGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#59f3c3" stopOpacity=".50"/><stop offset="1" stopColor="#59f3c3" stopOpacity="0"/></linearGradient></defs><XAxis dataKey="date" tick={{fill:'#ffffff77',fontSize:11}} tickLine={false} axisLine={false}/><YAxis tick={{fill:'#ffffff77',fontSize:11}} tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltip}/><Area type="monotone" dataKey="amount" stroke="#59f3c3" fill="url(#dailyGradient)" strokeWidth={3}/></AreaChart></ResponsiveContainer> : <ChartEmpty title="No daily rhythm yet"/>}</Card></Reveal><Reveal delay={.05}><Card className="p-6 sm:p-7"><div className="mb-5"><h3 className="text-2xl font-black">Category structure</h3><p className="mt-1 text-sm text-white/45">Where the month is really leaning.</p></div>{hasCategory ? <><ResponsiveContainer width="100%" height={250}><PieChart><Pie data={c.category} dataKey="value" nameKey="name" innerRadius={68} outerRadius={104} paddingAngle={3}>{c.category?.map((_:any,i:number)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={tooltip}/></PieChart></ResponsiveContainer><div className="mt-2 grid gap-2">{c.category?.slice(0,4).map((item:any,i:number)=><div key={item.name} className="flex items-center justify-between gap-3 text-sm"><span className="flex min-w-0 items-center gap-2 text-white/62"><span className="h-2.5 w-2.5 rounded-full" style={{background:colors[i%colors.length]}}/><span className="truncate">{item.name}</span></span><strong>{rupee(item.value)}</strong></div>)}</div></> : <ChartEmpty title="No category mix yet"/>}</Card></Reveal></section>

    <section className="grid gap-6 xl:grid-cols-[1fr_.85fr]"><Reveal><Card className="p-6 sm:p-7"><div className="mb-5 flex items-center justify-between gap-3"><div><h3 className="text-2xl font-black">Merchant leaderboard</h3><p className="mt-1 text-sm text-white/45">Top merchants after excluding noisy money movement.</p></div><Landmark className="text-saffronx"/></div>{hasMerchant ? <ResponsiveContainer width="100%" height={320}><BarChart data={c.merchant} layout="vertical" margin={{left:6,right:18,top:8,bottom:8}}><XAxis type="number" hide/><YAxis type="category" dataKey="name" tick={{fill:'#ffffff99',fontSize:12}} tickLine={false} axisLine={false} width={132}/><Tooltip contentStyle={tooltip}/><Bar dataKey="value" radius={[0,8,8,0]} fill="#ffb454" barSize={18}/></BarChart></ResponsiveContainer> : <ChartEmpty title="No merchant ranking yet"/>}</Card></Reveal><Reveal delay={.06}><Card className="p-6 sm:p-7"><div className="flex items-start justify-between gap-3"><div><h3 className="text-2xl font-black">Data quality</h3><p className="mt-1 text-sm text-white/45">Trust markers before you make decisions.</p></div><ShieldCheck className="text-emeraldx"/></div><div className="mt-6 grid gap-3"><Surface className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-sm text-white/65"><CheckCircle2 size={16} className="text-emeraldx"/> Subscriptions detected</span><Badge tone="good">{s.subscriptions?.length || 0}</Badge></Surface><Surface className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-sm text-white/65"><ReceiptText size={16} className="text-saffronx"/> Uncategorized</span><Badge tone={s.uncategorized ? 'warn':'good'}>{s.uncategorized || 0}</Badge></Surface><Surface className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-sm text-white/65"><ShieldCheck size={16} className="text-emeraldx"/> Low-confidence rows</span><Badge tone={s.low_confidence ? 'warn':'good'}>{s.low_confidence || 0}</Badge></Surface><Surface className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-sm text-white/65"><RefreshCcw size={16} className="text-white/55"/> Needs revisit</span><Badge tone={s.needs_revisit ? 'warn':'default'}>{s.needs_revisit || 0}</Badge></Surface></div></Card></Reveal></section>

    {!hasDaily && !hasCategory && <EmptyState icon={<IndianRupee/>} title="This month is ready for statements" body="Upload credit card, UPI, or bank exports and RupeeLens will build the dashboard from confirmed transactions only." />}
  </div>
}
