import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { BarChart3, Drama, ListChecks, ShieldCheck } from 'lucide-react';
import { api } from '../api';
import { currentMonth } from '../lib';
import { Badge, Card, EmptyState, Input, PageTitle, Surface } from '../components/ui';

const toneClass:any = { danger:'border-red-400/25 bg-red-400/10', warning:'border-saffronx/25 bg-saffronx/10', positive:'border-emeraldx/25 bg-emeraldx/10', info:'border-white/10 bg-white/7' };
const tone:any = { danger:'danger', warning:'warn', positive:'good', info:'default' };

function Evidence({evidence}:{evidence:any}){
  const items = Object.entries(evidence || {}).filter(([,v])=>typeof v !== 'object').slice(0,4);
  if(!items.length) return null;
  return <div className="mt-5 grid gap-2 sm:grid-cols-2">{items.map(([k,v])=><Surface key={k} className="px-3 py-2"><div className="text-[10px] font-black uppercase text-white/32">{k.replace(/_/g,' ')}</div><div className="mt-1 truncate text-sm font-black">{String(v)}</div></Surface>)}</div>
}

export default function Insights(){
  const [month,setMonth]=useState(currentMonth());
  const {data=[]}=useQuery({queryKey:['insights',month], queryFn:()=>api.insights(month)});
  return <div className="space-y-7">
    <PageTitle eyebrow="Insight Engine" title="Auditable money signals, not vague advice." description="Every card is generated by deterministic rules. Confidence, reasons, and evidence stay visible so you can trust why the signal appeared." action={<Input className="w-44" type="month" value={month} onChange={e=>setMonth(e.target.value)}/>} />

    <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{data.map((i:any,idx:number)=><motion.div key={`${i.type}-${i.title}`} initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:idx*.04}}><Card className={`min-h-[360px] p-6 ${toneClass[i.severity] || toneClass.info}`}><div className="mb-6 flex items-start justify-between gap-4"><div className="grid h-14 w-14 place-items-center rounded-md border border-white/10 bg-black/20 text-3xl">{i.emoji || '✨'}</div><div className="flex flex-col items-end gap-2"><Badge tone={tone[i.severity] || 'default'}>{i.severity}</Badge><Badge tone={i.confidence_label==='high'?'good':i.confidence_label==='medium'?'warn':'danger'}>{i.confidence_label || 'medium'} confidence</Badge></div></div><div className="flex items-center gap-2 text-xs font-black uppercase text-white/34"><BarChart3 size={14}/>{i.type || 'signal'} · {i.metric || 'metric'}</div><h3 className="mt-3 text-2xl font-black leading-tight">{i.title}</h3><p className="mt-3 text-sm leading-6 text-white/62">{i.body}</p><div className="mt-5 rounded-md border border-white/10 bg-black/16 p-4"><div className="mb-3 flex items-center gap-2 text-xs font-black uppercase text-white/42"><ListChecks size={14}/> Why this appeared</div><ul className="space-y-2 text-sm leading-5 text-white/62">{(i.reasons || ['Evidence-led, no invented transactions']).slice(0,3).map((r:string)=><li key={r} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-emeraldx"/>{r}</li>)}</ul></div><Evidence evidence={i.evidence}/><div className="mt-5 flex items-center gap-2 text-xs font-bold text-white/35"><ShieldCheck size={14}/> Deterministic rule · confidence {Math.round((i.confidence || 0)*100)}%</div></Card></motion.div>)}</div>

    {!data.length && <EmptyState icon={<Drama/>} title="No insights yet" body="Upload or seed transactions and RupeeLens will generate deterministic monthly signals with evidence and confidence labels." />}
  </div>
}
