import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Filter, ReceiptText, Search, ShieldAlert } from 'lucide-react';
import { api } from '../api';
import { currentMonth, rupee } from '../lib';
import { Badge, Card, EmptyState, Input, PageTitle, Reveal, Select, Surface } from '../components/ui';

const categories=['Food & Dining','Groceries','Transport','Fuel','Shopping','Entertainment','Travel','Utilities','Subscriptions','Credit Card Payment','Bank Transfer','UPI Transfer','Miscellaneous','Uncategorized'];
const modes=['all','credit_card','upi','bank','cash','manual'];

function confidenceTone(score:number){ if(score>=.75) return 'good'; if(score>=.5) return 'warn'; return 'danger'; }
function flagTone(t:any){ if(t.is_refund) return 'good'; if(t.is_excluded_from_spend) return 'default'; if(t.revisit_flag) return 'warn'; return 'good'; }

export default function Transactions(){
  const [month,setMonth]=useState(currentMonth());
  const [merchant,setMerchant]=useState('');
  const [category,setCategory]=useState('');
  const [mode,setMode]=useState('all');
  const [revisit,setRevisit]=useState(false);
  const qc=useQueryClient();
  const query = useMemo(()=>{ const params = new URLSearchParams(); params.set('month',month); if(category) params.set('category',category); if(merchant) params.set('merchant',merchant); if(mode !== 'all') params.set('payment_mode',mode); if(revisit) params.set('revisit','true'); return `?${params.toString()}`; },[month,category,merchant,mode,revisit]);
  const txs=useQuery({queryKey:['tx',query], queryFn:()=>api.transactions(query)});
  const patch=useMutation({mutationFn:({id,body}:{id:number;body:any})=>api.patchTx(id,body), onSuccess:()=>qc.invalidateQueries({queryKey:['tx']})});
  const rows = txs.data || [];
  const total = rows.filter((t:any)=>!t.is_excluded_from_spend && !t.is_refund).reduce((sum:number,t:any)=>sum + Number(t.amount || 0),0);

  return <div className="space-y-6">
    <PageTitle eyebrow="Transactions" title="Fast ledger review, without losing context." description="Filter, correct categories, add remarks, and mark revisit items. Every row keeps raw statement text visible for auditability." action={<Badge>{rows.length} rows</Badge>} />

    <Reveal><Card className="p-5"><div className="grid gap-3 lg:grid-cols-[160px_1fr_190px_150px_auto]"><Input type="month" value={month} onChange={e=>setMonth(e.target.value)}/><div className="relative"><Search className="pointer-events-none absolute left-3 top-3 text-white/34" size={16}/><Input className="pl-9" placeholder="Search merchant or raw description" value={merchant} onChange={e=>setMerchant(e.target.value)}/></div><Select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</Select><Select value={mode} onChange={e=>setMode(e.target.value)}>{modes.map(m=><option key={m} value={m}>{m === 'all' ? 'All modes' : m}</option>)}</Select><button onClick={()=>setRevisit(v=>!v)} className={`inline-flex min-h-10 items-center justify-center gap-2 rounded-md border px-4 py-2 text-sm font-black transition ${revisit?'border-saffronx/35 bg-saffronx/14 text-saffronx':'border-white/12 bg-white/6 text-white/65 hover:bg-white/10'}`}><Filter size={16}/> Revisit</button></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Surface><div className="text-xs text-white/38">Visible included spend</div><div className="mt-1 text-xl font-black">{rupee(total)}</div></Surface><Surface><div className="text-xs text-white/38">Excluded/refunds</div><div className="mt-1 text-xl font-black">{rows.filter((t:any)=>t.is_excluded_from_spend || t.is_refund).length}</div></Surface><Surface><div className="text-xs text-white/38">Low confidence</div><div className="mt-1 text-xl font-black">{rows.filter((t:any)=>(t.confidence_score||0)<.55).length}</div></Surface></div></Card></Reveal>

    <Reveal><Card className="hidden overflow-hidden p-0 lg:block"><div className="table-scroll max-h-[680px] overflow-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="sticky top-0 z-10 border-b border-white/10 bg-[#07110f]/95 text-xs font-black uppercase text-white/42 backdrop-blur"><tr><th className="px-5 py-4">Date</th><th>Merchant</th><th>Amount</th><th>Mode</th><th>Category</th><th>Confidence</th><th>Remark</th><th>Flags</th></tr></thead><tbody>{rows.map((t:any)=><tr key={t.id} className="border-t border-white/7 transition hover:bg-white/5"><td className="px-5 py-4 text-white/58">{t.transaction_date}</td><td><div className="font-black">{t.merchant_normalized}</div><div className="max-w-sm truncate text-xs text-white/35">{t.description_raw}</div></td><td className={`font-black ${t.direction==='credit' || t.is_refund ? 'text-emeraldx':'text-white'}`}>{rupee(t.amount)}</td><td><Badge>{t.payment_mode}</Badge></td><td className="w-56"><Select value={t.category} onChange={e=>patch.mutate({id:t.id, body:{category:e.target.value}})}>{categories.map(c=><option key={c}>{c}</option>)}</Select></td><td><Badge tone={confidenceTone(t.confidence_score||0) as any}>{Math.round((t.confidence_score||0)*100)}%</Badge></td><td className="w-72"><Input defaultValue={t.remark||''} placeholder="Add note" onBlur={e=>patch.mutate({id:t.id, body:{remark:e.target.value}})}/></td><td><div className="flex flex-wrap items-center gap-1.5">{t.is_excluded_from_spend&&<Badge>excluded</Badge>}{t.is_refund&&<Badge tone="good">refund</Badge>}{(t.confidence_score||0)<.55&&<Badge tone="danger">review</Badge>}<label className="inline-flex items-center gap-1 rounded-full border border-white/10 bg-white/6 px-2 py-1 text-xs text-white/65"><input type="checkbox" checked={t.revisit_flag} onChange={e=>patch.mutate({id:t.id, body:{revisit_flag:e.target.checked}})}/> revisit</label></div></td></tr>)}</tbody></table></div></Card></Reveal>

    <div className="grid gap-3 lg:hidden">{rows.map((t:any,idx:number)=><Reveal key={t.id} delay={idx*.02}><Card className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate font-black">{t.merchant_normalized}</div><div className="mt-1 text-xs text-white/38">{t.transaction_date} · {t.payment_mode}</div></div><div className="text-right"><div className="font-black">{rupee(t.amount)}</div><Badge tone={flagTone(t) as any}>{t.is_refund?'refund':t.is_excluded_from_spend?'excluded':t.revisit_flag?'revisit':'spend'}</Badge></div></div><div className="mt-4 grid gap-3"><Select value={t.category} onChange={e=>patch.mutate({id:t.id, body:{category:e.target.value}})}>{categories.map(c=><option key={c}>{c}</option>)}</Select><Input defaultValue={t.remark||''} placeholder="Remark" onBlur={e=>patch.mutate({id:t.id, body:{remark:e.target.value}})}/></div><div className="mt-3 flex items-center justify-between gap-3 text-xs text-white/42"><span className="truncate">{t.description_raw}</span><Badge tone={confidenceTone(t.confidence_score||0) as any}>{Math.round((t.confidence_score||0)*100)}%</Badge></div></Card></Reveal>)}</div>

    {!txs.isLoading && !rows.length && <EmptyState icon={<ReceiptText/>} title="No transactions match this view" body="Try a different month, clear filters, or upload and confirm a statement batch first." />}
    {(rows.some((t:any)=>(t.confidence_score||0)<.55) || rows.some((t:any)=>t.category==='Uncategorized')) && <Card className="border-saffronx/20 bg-saffronx/8 p-5"><div className="flex gap-3"><ShieldAlert className="shrink-0 text-saffronx"/><div><div className="font-black">Review queue available</div><p className="mt-1 text-sm leading-6 text-white/58">Low-confidence and uncategorized rows are worth correcting first. Merchant rules will improve future imports.</p></div></div></Card>}
  </div>
}
