import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, CheckCircle2, FileSpreadsheet, ListChecks, UploadCloud, Wand2 } from 'lucide-react';
import { api } from '../api';
import { rupee } from '../lib';
import { Badge, Button, Card, EmptyState, GhostButton, Input, PageTitle, Reveal, Select, Surface } from '../components/ui';

const sources = ['Credit Card Statement PDF','Credit Card CSV/XLSX','UPI CSV/XLSX','Bank Statement','Manual Import Template'];
const steps = ['Upload','Parse','Review','Fix','Confirm'];

export default function UploadCenter(){
  const qc=useQueryClient();
  const [source,setSource]=useState('UPI CSV/XLSX');
  const [account,setAccount]=useState('');
  const [files,setFiles]=useState<FileList|null>(null);
  const accounts=useQuery({queryKey:['accounts'],queryFn:api.accounts});
  const uploads=useQuery({queryKey:['uploads'],queryFn:api.uploads});
  const selectedFiles = useMemo(()=>Array.from(files ?? []),[files]);
  const upload=useMutation({mutationFn:()=>{const fd=new FormData(); fd.append('source_type',source); if(account) fd.append('account_id',account); selectedFiles.forEach((f: File) => fd.append('files', f)); return api.upload(fd)}, onSuccess:()=>qc.invalidateQueries({queryKey:['uploads']})});
  const confirm=useMutation({mutationFn:(id:number)=>api.confirmUpload(id), onSuccess:()=>{qc.invalidateQueries({queryKey:['uploads']}); qc.invalidateQueries({queryKey:['summary']}); qc.invalidateQueries({queryKey:['charts']})}});

  return <div className="space-y-7">
    <PageTitle eyebrow="Upload Center" title="Import statements with a review gate." description="RupeeLens treats every upload as sensitive financial data. Files are parsed into preview batches first, then you confirm only the rows that make sense." action={<Badge tone="good">Upload → Parse → Review → Fix → Confirm</Badge>} />

    <Reveal><Card className="p-6 sm:p-7"><div className="grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><div><h3 className="text-2xl font-black">Import setup</h3><p className="mt-2 text-sm leading-6 text-white/50">Pick the source and account before selecting files. Unknown column formats will still land in preview rather than touching your ledger.</p><div className="mt-6 grid gap-3"><Select value={source} onChange={e=>setSource(e.target.value)}>{sources.map(x=><option key={x}>{x}</option>)}</Select><Select value={account} onChange={e=>setAccount(e.target.value)}><option value="">No account selected</option>{accounts.data?.map((a:any)=><option key={a.id} value={a.id}>{a.name}</option>)}</Select></div><div className="mt-5 flex flex-wrap gap-2">{steps.map((step,i)=><Badge key={step} tone={i<2?'good':'default'}>{i+1}. {step}</Badge>)}</div></div><div><label className="group grid min-h-64 cursor-pointer place-items-center rounded-md border border-dashed border-emeraldx/30 bg-emeraldx/8 p-6 text-center transition hover:border-emeraldx/55 hover:bg-emeraldx/12"><input className="hidden" type="file" multiple onChange={e=>setFiles(e.target.files)}/><div><div className="mx-auto grid h-16 w-16 place-items-center rounded-md border border-emeraldx/25 bg-emeraldx/12 text-emeraldx transition group-hover:scale-105"><UploadCloud size={30}/></div><h4 className="mt-5 text-2xl font-black">Drop statement exports here</h4><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-white/50">CSV, XLSX, and text-extractable PDFs are parsed into a secure preview batch before import.</p><div className="mt-5 flex flex-wrap justify-center gap-2">{selectedFiles.length ? selectedFiles.map(file=><Badge key={file.name}>{file.name}</Badge>) : <Badge>Choose one or more files</Badge>}</div></div></label><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-white/42">Selected rows are not imported until confirmed.</p><Button disabled={!selectedFiles.length || upload.isPending} onClick={()=>upload.mutate()}><Wand2 size={17}/> Preview upload</Button></div></div></div></Card></Reveal>

    <div className="grid gap-4">{uploads.data?.map((batch:any,idx:number)=><Reveal key={batch.id} delay={idx*.03}><Card className="overflow-hidden p-0"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-white/10 p-5 sm:p-6"><div className="flex min-w-0 gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-md border border-white/10 bg-white/8 text-emeraldx"><FileSpreadsheet/></div><div className="min-w-0"><div className="truncate text-lg font-black">{batch.source_file_name}</div><div className="mt-1 text-sm text-white/45">{batch.source_type} · {batch.parsed_rows?.length || 0} parsed rows · {batch.errors?.length || 0} errors</div><div className="mt-3 flex flex-wrap gap-2"><Badge tone={batch.status==='imported'?'good':'warn'}>{batch.status}</Badge><Badge>{batch.created_at?.slice?.(0,10) || 'preview batch'}</Badge></div></div></div><div className="flex gap-2">{batch.status==='preview' && <Button onClick={()=>confirm.mutate(batch.id)} disabled={confirm.isPending}><CheckCircle2 size={17}/> Confirm import</Button>}<GhostButton><ListChecks size={16}/> Review</GhostButton></div></div>{batch.errors?.length > 0 && <div className="border-b border-saffronx/20 bg-saffronx/8 px-6 py-3 text-sm text-saffronx"><AlertTriangle className="mr-2 inline" size={16}/>{batch.errors[0]}</div>}<div className="table-scroll overflow-auto"><table className="w-full min-w-[840px] text-left text-sm"><thead className="bg-white/5 text-xs font-black uppercase text-white/42"><tr><th className="px-5 py-3">Date</th><th>Merchant</th><th>Category</th><th>Amount</th><th>Status</th><th>Confidence</th></tr></thead><tbody>{batch.parsed_rows?.slice(0,8).map((r:any,i:number)=><tr key={i} className="border-t border-white/8 transition hover:bg-white/5"><td className="px-5 py-3 text-white/58">{r.transaction_date}</td><td><div className="font-black">{r.merchant_normalized}</div><div className="max-w-sm truncate text-xs text-white/36">{r.description_raw}</div></td><td>{r.category}</td><td className="font-black">{rupee(r.amount)}</td><td>{r.is_excluded_from_spend?<Badge>Excluded</Badge>:<Badge tone="good">Spend</Badge>}</td><td>{Math.round((r.confidence_score||0)*100)}%</td></tr>)}</tbody></table></div></Card></Reveal>)}</div>

    {!uploads.data?.length && <EmptyState icon={<UploadCloud/>} title="No import batches yet" body="Start with a UPI export, credit card CSV, or bank statement. RupeeLens will parse rows into a reviewable batch before changing your data." />}
  </div>
}
